### ISSUE TITLE
A number of links point to the localhost.

### ISSUE THREAD

**Issue by SuzeShardlow** [yougotthisconf/couch.yougotthis.io#17]
Sorry @phazonoverload.  I started doing this and then realised there were more than one link to Twitter, Discord etc so I have stopped creating a new issue for each one.

**Comment by phazonoverload** [comment]
Aha good find. I should have saved the snapshot from the live version. My bad. Will get this fixed soon.

**Comment by SuzeShardlow** [comment]
I think I captured them all in the PRs :)

https://github.com/yougotthisconf/couch.yougotthis.io/pulls
